package com.ollo.exam.cheque;

import org.junit.Test;
import static org.junit.Assert.*;

/**
 * Base tests around Cheque interface.
 * <p/>
 * Do not edit this file.  Custom tests can be added in {@link MyChequeTest}.
 */
public abstract class ChequeTest {

	/**
	 * Implement to return custom Cheque interface.
	 * @return	The Cheque interface to test
	 */
	public abstract Cheque createCheque();
	
	/*
	 * Do not edit.
	 */
    @Test
	public void testOneDollarNoCents() throws Exception {
		
		Cheque cheque = createCheque();
		
		String expected = "One dollar and no cents.";
		String actual = cheque.inWords(1.00);

		assertEquals(expected, actual);
	}
	
	/*
	 * Do not edit.
	 */
	@Test
	public void testTwoDollarsNoCents() throws Exception {
		
		Cheque cheque = createCheque();
		
		String expected = "Two dollars and no cents.";
		String actual = cheque.inWords(2.00);
		
		assertEquals(expected, actual);
	}
	
	/*
	 * Do not edit.
	 */
	@Test
	public void testTwoDollarsSixtySevenCents() throws Exception {
		
		Cheque cheque = createCheque();
		
		String expected = "Two dollars and sixty seven cents.";
		String actual = cheque.inWords(2.67);
		
		assertEquals(expected, actual);
	}
	
	/*
	 * Do not edit.
	 */
	@Test
	public void testLowerBound() throws Exception {
		
		Cheque cheque = createCheque();
		
		try {
			String actual = cheque.inWords(-1.00);
			fail("Should have thrown ChequeException");
		} catch (ChequeException e) {
			// Expected
		}
	}
	
	/*
	 * Do not edit.
	 */
	@Test
	public void testUpperBound() throws Exception {
		
		Cheque cheque = createCheque();
		
		try {
			String actual = cheque.inWords(10000000.01);
			fail("Should have thrown ChequeException");
		} catch (ChequeException e) {
			// Expected
		}
	}
}